export const enum TileKind {
  Empty = 0,
  Stone = 1,
  Sand = 2,
  Platform = 3,
  Magnet = 4,
  Iron = 5,
  Conduit = 6,
  Sensor = 7,
  Inverter = 8,
  Combiner = 9,
  Rectifier = 10,
  Multiplier = 11,
  Subtractor = 12,
  ChargeSensor = 13,
  Selector = 14,
  WireCrossing = 15,
  Glass = 16,
  IronOre = 17,
  Furnace = 18,
  Conveyor = 19,
  Delivery = 20,
  Victory = 21,
  FixedCharge = 22,
  Spark = 23,
  Piston = 24,
  PistonBase = 25,
  PistonArm = 26,
  Delay = 27,
  Counter = 28,
  Rom = 29,
  Welder = 30,
  Splitter = 31,
  Duplicator = 32,
  Monitor = 33,
  Grapher = 34,
  Checker = 35,
  RuneArray = 36,
  Assembler = 37,
  Equality = 38,
  Minimum = 39,
  Maximum = 40,
  Rotator = 41,
  Dirt = 42,
  Gold = 43,
  Silver = 44,
  Ruby = 45,
  Sapphire = 46,
  Emerald = 47,
  Diamond = 48,
  Amethyst = 49,
  Mithril = 50,
  CopperOre = 51,
  Copper = 52,
  Wood = 53,
  Comparer = 54,
  LaserSplitter = 55,
  Drill = 56,
  Grinder = 57,
  Floatstone = 58,
  Discard = 59,
  Lut = 60,
  Fastener = 61,
  Slider = 62,
  Thruster = 63,
  ControlledThruster = 64,
  MovementSensor = 65,
  LevitationProjector = 66,
  ForceProjector = 67,
  DelayGate = 68,
  BlockComparer = 69,
  MagicLink = 70,
  IndestructibleConduit = 71,
  Dismantler = 72,
  BeamBlockSensor = 73,
  BeamBodySensor = 74,
  Bell = 75,
}

export const enum Direction {
  Up = 0,
  Right = 1,
  Down = 2,
  Left = 3,
}

export const enum WeldSide {
  None = 0,
  Up = 1 << Direction.Up,
  Right = 1 << Direction.Right,
  Down = 1 << Direction.Down,
  Left = 1 << Direction.Left,
  All = Up | Right | Down | Left,
}

export const enum TileDecorationStyle {
  None = 0,
  Crack = 1,
  Grains = 2,
  Magnet = 3,
  Iron = 4,
  Conduit = 5,
  Sensor = 6,
  Inverter = 7,
  Combiner = 8,
  Rectifier = 9,
  Multiplier = 10,
  Subtractor = 11,
  ChargeSensor = 12,
  Selector = 13,
  WireCrossing = 14,
  Furnace = 15,
  Conveyor = 16,
  Delivery = 17,
  Victory = 18,
  FixedCharge = 19,
  Spark = 20,
  Piston = 21,
  PistonBase = 22,
  PistonArm = 23,
  Delay = 24,
  Counter = 25,
  Rom = 26,
  Welder = 27,
  Splitter = 28,
  Duplicator = 29,
  Monitor = 30,
  Grapher = 31,
  Checker = 32,
  RuneArray = 33,
  Assembler = 34,
  Equality = 35,
  Minimum = 36,
  Maximum = 37,
  Rotator = 38,
  Glass = 39,
  Gem = 40,
  Wood = 41,
  SquareGrains = 42,
  Comparer = 43,
  LaserSplitter = 44,
  Drill = 45,
  Grinder = 46,
  Floatstone = 47,
  Discard = 48,
  Lut = 49,
  Fastener = 50,
  Slider = 51,
  Thruster = 52,
  ControlledThruster = 53,
  MovementSensor = 54,
  LevitationProjector = 55,
  ForceProjector = 56,
  DelayGate = 57,
  MagicLink = 58,
  IndestructibleConduit = 59,
  Dismantler = 60,
  BeamBlockSensor = 61,
  Bell = 62,
}

export const enum PaletteCategory {
  RawMaterials = 0,
  Motion = 3,
  Transformation = 4,
  CircuitBasic = 5,
  CircuitGates = 6,
  CircuitComplex = 7,
  PuzzleTools = 8,
}

export interface TileDefinition {
  readonly name: string;
  /** Single UTF-16 code unit used by the compact board format. */
  readonly boardCode: string;
  /** Suggested puzzle-authoring price; individual puzzle catalogs override it. */
  readonly defaultPrice: number;
  /** Sandbox component-palette presentation. Empty tiles are not palette entries. */
  readonly palette: {
    readonly order: number;
    readonly category: PaletteCategory;
    readonly description: string;
    readonly extendedDescription: readonly string[];
  } | null;
  readonly affectedByGravity: boolean;
  /** Anchors the whole welded body against all motion; omitted means movable. */
  readonly immovable?: boolean;
  /** Restricts translation to the facing axis, in either direction; rotation remains allowed. */
  readonly slidesAlongOrientation?: boolean;
  /** Hidden from occupancy sensors and transparent to charge-sensor rays; omitted means detectable. */
  readonly invisibleToSensor?: boolean;
  /** Immune to destructive tools such as drills; omitted means destructible. */
  readonly indestructible?: boolean;
  /** Machinery cannot create or cut an edge when both endpoints are protected; editing is unaffected. */
  readonly runtimeWeldProtected?: boolean;
  /** Unwelded tiles break when a gravity fall longer than one cell stops. */
  readonly fragile?: boolean;
  readonly weldableSides: WeldSide;
  readonly excludesFacingWeld: boolean;
  readonly usesOrientation: boolean;
  /** Reflects local left/right before applying orientation; omitted means symmetric. */
  readonly usesMirroring?: boolean;
  readonly circuitPorts: WeldSide;
  /** Isolated input or sensing ports relative to an upward-facing tile. */
  readonly circuitInputPorts: WeldSide;
  /** Isolated output ports relative to an upward-facing tile. */
  readonly circuitOutputPorts: WeldSide;
  readonly slidesDiagonally: boolean;
  readonly magnetic: boolean;
  readonly attractionRange: number;
  readonly fill: string;
  readonly decorationStyle: TileDecorationStyle;
  readonly decorationColor: string;
}

export function directionX(direction: Direction): -1 | 0 | 1 {
  return direction === Direction.Right ? 1 : direction === Direction.Left ? -1 : 0;
}

export function directionY(direction: Direction): -1 | 0 | 1 {
  return direction === Direction.Down ? 1 : direction === Direction.Up ? -1 : 0;
}

export function oppositeDirection(direction: Direction): Direction {
  return ((direction + 2) & 3) as Direction;
}

export function flipDirectionHorizontally(direction: Direction): Direction {
  if (direction === Direction.Right) {
    return Direction.Left;
  }
  if (direction === Direction.Left) {
    return Direction.Right;
  }
  return direction;
}

export function flipDirectionVertically(direction: Direction): Direction {
  if (direction === Direction.Up) {
    return Direction.Down;
  }
  if (direction === Direction.Down) {
    return Direction.Up;
  }
  return direction;
}

export const TILE_DEFINITIONS: Readonly<Record<TileKind, TileDefinition>> = {
  [TileKind.Empty]: {
    name: "Empty",
    boardCode: ".",
    defaultPrice: 0,
    palette: null,
    affectedByGravity: false,
    slidesDiagonally: false,
    weldableSides: WeldSide.None,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "transparent",
    decorationStyle: TileDecorationStyle.None,
    decorationColor: "transparent",
  },
  [TileKind.Stone]: {
    name: "Stone",
    boardCode: "#",
    defaultPrice: 1,
    palette: {
      order: 41,
      category: PaletteCategory.RawMaterials,
      description: "Solid block affected by gravity.",
      extendedDescription: ["Falls one cell per tick when unsupported. Weld it to neighboring blocks to build a rigid body."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#66717d",
    decorationStyle: TileDecorationStyle.Crack,
    decorationColor: "#525d68",
  },
  [TileKind.Sand]: {
    name: "Sand",
    boardCode: ":",
    defaultPrice: 1,
    palette: {
      order: 44,
      category: PaletteCategory.RawMaterials,
      description: "Falls downward or diagonally downward. Cannot be welded.",
      extendedDescription: ["Falls straight down first, then tries a downward diagonal around an obstacle determined by parity of tick number and coordinate. A furnace turns sand into glass in four ticks."],
    },
    affectedByGravity: true,
    slidesDiagonally: true,
    weldableSides: WeldSide.None,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#e7ad4f",
    decorationStyle: TileDecorationStyle.Grains,
    decorationColor: "#8d5b26",
  },
  [TileKind.Platform]: {
    name: "Platform",
    boardCode: "=",
    defaultPrice: 10,
    palette: {
      order: 25,
      category: PaletteCategory.PuzzleTools,
      description: "Fixed indestructible block not affected by gravity.",
      extendedDescription: ["Anchors its entire welded body: it cannot fall or be pushed. Indestructible: drills cannot remove it. Weld-protected - cannot be welded/split at runtime at sides shared with other weld-protected blocks."],
    },
    affectedByGravity: false,
    immovable: true,
    indestructible: true,
    runtimeWeldProtected: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#595f7d",
    decorationStyle: TileDecorationStyle.Iron,
    decorationColor: "#2f2b43",
  },
  [TileKind.Floatstone]: {
    name: "Floatstone",
    boardCode: "z",
    defaultPrice: 20,
    palette: {
      order: 64,
      category: PaletteCategory.Motion,
      description: "Holds its welded body aloft, but can still be pushed.",
      extendedDescription: ["Prevents its entire welded body from falling on its own. An independent falling body on top pushes it downward if the whole chain has room.", "Pistons, conveyors, and rotators can move it. Welding it to a platform still anchors the body. It needs no charge."],
    },
    affectedByGravity: false,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#476d83",
    decorationStyle: TileDecorationStyle.Floatstone,
    decorationColor: "#bdeeff",
  },
  [TileKind.LevitationProjector]: {
    name: "Levitation Projector",
    boardCode: "%",
    defaultPrice: 30,
    palette: {
      order: 65,
      category: PaletteCategory.Motion,
      description: "Disables gravity along its forward beam, to the edge of the grid or an opposing levitation projector. Disabled by -1 rear input.",
      extendedDescription: ["The isolated rear input reads the previous tick's charge: -1 disables the beam; zero, +1, or a disconnected input enables it. Has no circuit output. Rear control also works through rune-array ports.", "Projects through blocks and gaps from one cell ahead to the front face of the first opposing levitation projector, even if that projector is disabled, or this board's boundary. Other projector orientations do not stop the beam. Touching any tile with the beam holds its entire welded body aloft.", "Affected bodies can still be moved by machinery or pushed down by independent falling weight. Platforms and sliders retain their movement restrictions. Leaving the beam restores gravity on the next tick.", "Facing projectors confine their beams to the space between them; they do not hold each other aloft. The projector itself falls normally unless supported or its body intersects another beam. Beams do not cross rune-array boundaries."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Down,
    circuitInputPorts: WeldSide.Down,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#416c80",
    decorationStyle: TileDecorationStyle.LevitationProjector,
    decorationColor: "#bdeeff",
  },
  [TileKind.ForceProjector]: {
    name: "Force Projector",
    boardCode: "&",
    defaultPrice: 30,
    palette: {
      order: 61,
      category: PaletteCategory.Motion,
      description: "Pushes the first block ahead on rear +1, or pulls it on rear -1.",
      extendedDescription: ["The isolated rear input reads the previous tick's charge: +1 pushes the first occupied cell ahead away from the projector; -1 pulls it toward the projector. Zero or a disconnected input applies no force. Has no circuit output.", "Looks through empty space only, stopping at any block, including glass and fixed terrain, or this board's boundary. A target in the projector's own welded body blocks the ray without receiving force. Beams do not cross rune-array boundaries.", "Force combines with conveyors and thrusters, moving the target's welded body and pushing movable contact chains under their ordinary slider, collision, and jam rules. Powered pushing takes priority over gravity and can lift ordinary blocks without floatstone or levitation. Successful driven movement breaks carried fasteners.", "The projector falls normally and can be welded on every side. Applying force causes no recoil and does not hold the projector aloft. Targets are observed before production; removed or replacement tiles do not inherit a pending command."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Down,
    circuitInputPorts: WeldSide.Down,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#805f45",
    decorationStyle: TileDecorationStyle.ForceProjector,
    decorationColor: "#ffe0a3",
  },
  [TileKind.MagicLink]: {
    name: "Magic Link",
    boardCode: "}",
    defaultPrice: 15,
    palette: {
      order: 73,
      category: PaletteCategory.Motion,
      description: "Joins distant facing links into one body; rear -1 disables it.",
      extendedDescription: ["Looks forward through gaps, ordinary blocks, and differently oriented magic links to the first opposite-facing magic link. A disabled opposing link still stops the ray, but makes no connection.", "A rear input of -1 disables every connection involving this link. Both endpoints must be enabled to create a link.", "Each link joins both bodies into one mechanical body. Multiple incoming links and chains merge transitively, sharing movement, support, and movement restrictions."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Down,
    circuitInputPorts: WeldSide.Down,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#69557e",
    decorationStyle: TileDecorationStyle.MagicLink,
    decorationColor: "#f2d49a",
  },
  [TileKind.Fastener]: {
    name: "Fastener",
    boardCode: "y",
    defaultPrice: 4,
    palette: {
      order: 66,
      category: PaletteCategory.Motion,
      description: "Holds its welded body aloft until machinery moves it and breaks the fastener.",
      extendedDescription: ["Prevents its entire welded body from falling on its own. Needs no charge and can be welded on every side.", "A successful conveyor or thruster move, piston push or pull, or rotator turn destroys the fastener and its welds after moving the body. Blocked machinery attempts do not break it.", "An independent falling body can push it downward if the whole chain has room; gravity-driven movement does not break it. Welding it to a platform still anchors the body."],
    },
    affectedByGravity: false,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#66594a",
    decorationStyle: TileDecorationStyle.Fastener,
    decorationColor: "#e3c693",
  },
  [TileKind.Bell]: {
    name: "Bell",
    boardCode: "5",
    defaultPrice: 5,
    palette: {
      order: 78,
      category: PaletteCategory.Motion,
      description: "Rings on net horizontal movement; larger welded bodies sound lower.",
      extendedDescription: ["Rings when its final horizontal position differs from the start of the tick. Pure vertical movement and motion returning to the same horizontal position are silent. Inner bells measure movement within their own board, not movement of the containing rune array.", "Pitch descends across one octave as its final welded body grows from 1 to 8 blocks, counting the bell itself. Larger bodies use the 8-block pitch.", "Falls under ordinary gravity and can be welded on every side. Has no circuit ports, needs no charge, and ignores orientation.", "Sound plays only in the browser with audio enabled and simulation speed below 10 ticks per second."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#705039",
    decorationStyle: TileDecorationStyle.Bell,
    decorationColor: "#e5bb60",
  },
  [TileKind.Slider]: {
    name: "Slider",
    boardCode: "~",
    defaultPrice: 20,
    palette: {
      order: 67,
      category: PaletteCategory.Motion,
      description: "Restricts its welded body to movement along the marked axis.",
      extendedDescription: ["Moves in either direction along its rails, never across them. Vertical sliders can fall; horizontal sliders hold their welded body aloft, even under falling weight.", "Every welded slider adds its constraint: perpendicular sliders prevent all translation. Pistons and conveyors must obey the same rails.", "Rotate to change the permitted axis. Rotators can turn the body freely, subject to their usual collisions; the rails turn with it."],
    },
    affectedByGravity: true,
    slidesAlongOrientation: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#536c69",
    decorationStyle: TileDecorationStyle.Slider,
    decorationColor: "#c5e2ce",
  },
  [TileKind.Thruster]: {
    name: "Thruster",
    boardCode: "^",
    defaultPrice: 20,
    palette: {
      order: 69,
      category: PaletteCategory.Motion,
      description: "Holds its welded body aloft and drives it forward, pushing obstacles.",
      extendedDescription: ["Always applies forward thrust without charge. Moves its welded body one cell per tick and pushes movable contact chains; platforms, boundaries, and transverse sliders block the whole move.", "Thrust combines with other thrusters and conveyor forces on the same body. Opposing forces cancel; incompatible moves by separate bodies jam. Powered pushing takes priority over gravity, lifting unwelded loads and reserving destinations before falling bodies."],
    },
    affectedByGravity: false,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#795448",
    decorationStyle: TileDecorationStyle.Thruster,
    decorationColor: "#ffe0a3",
  },
  [TileKind.ControlledThruster]: {
    name: "Controlled Thruster",
    boardCode: "!",
    defaultPrice: 40,
    palette: {
      order: 70,
      category: PaletteCategory.Motion,
      description: "Holds its welded body aloft and thrusts toward a +1 input.",
      extendedDescription: ["Four isolated input ports read the previous tick's charges. Exactly one +1 input applies thrust toward that side; 0 and -1 are ignored. Two or more +1 inputs jam this thruster, producing no force.", "Holds its welded body aloft even while idle. Needs welded circuit connections, but never passes charge between its inputs. No rotation is needed: each side always controls movement toward itself.", "Shares ordinary thruster pushing, force sums, slider restrictions, priority over gravity, and collision rules. A jammed input does not anchor the body against other machinery."],
    },
    affectedByGravity: false,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.All,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#795448",
    decorationStyle: TileDecorationStyle.ControlledThruster,
    decorationColor: "#ffe0a3",
  },
  [TileKind.Magnet]: {
    name: "Lodestone",
    boardCode: "L",
    defaultPrice: 10,
    palette: {
      order: 26,
      category: PaletteCategory.Motion,
      description: "Holds magnetic blocks on its pointed side.",
      extendedDescription: ["Acts on the immediately adjacent magnetic block on its pointed side, holding the attached bodies against gravity. The pointed side cannot be welded. It needs no circuit charge."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: true,
    usesOrientation: true,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 1,
    fill: "#b94b52",
    decorationStyle: TileDecorationStyle.Magnet,
    decorationColor: "#f3e5c8",
  },
  [TileKind.Iron]: {
    name: "Iron",
    boardCode: "i",
    defaultPrice: 4,
    palette: {
      order: 47,
      category: PaletteCategory.RawMaterials,
      description: "Magnetic structural block affected by gravity and smelted from iron ore.",
      extendedDescription: ["Lodestones can hold iron; ordinary nonmagnetic materials do not attach this way. Weld iron to a larger body to carry that body with it."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: true,
    attractionRange: 0,
    fill: "#718a9b",
    decorationStyle: TileDecorationStyle.Iron,
    decorationColor: "#d5e1e7",
  },
  [TileKind.Conduit]: {
    name: "Channel",
    boardCode: "C",
    defaultPrice: 2,
    palette: {
      order: 9,
      category: PaletteCategory.CircuitBasic,
      description: "Shares charge across welded circuit blocks.",
      extendedDescription: ["Weld circuit ports together to form a network. Every connected channel shares the sign of the total driver charge: positive and negative drivers cancel, and an undriven network is neutral."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#69727b",
    decorationStyle: TileDecorationStyle.Conduit,
    decorationColor: "#162f4b",
  },
  [TileKind.IndestructibleConduit]: {
    name: "Indestructible Channel",
    boardCode: "{",
    defaultPrice: 10,
    palette: {
      order: 38,
      category: PaletteCategory.PuzzleTools,
      description: "Shares charge across welded circuit blocks. Indestructible and weld-protected.",
      extendedDescription: ["Carries charge like a channel: every connected port shares the sign of the total driver charge. Positive and negative drivers cancel, and an undriven network is neutral.", "Indestructible, but not fixed: falls and moves with its welded body like an ordinary channel.", "Weld-protected - cannot be welded/split at runtime at sides shared with other weld-protected blocks."],
    },
    affectedByGravity: true,
    indestructible: true,
    runtimeWeldProtected: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#595f7d",
    decorationStyle: TileDecorationStyle.IndestructibleConduit,
    decorationColor: "#2f2b43",
  },
  [TileKind.DelayGate]: {
    name: "Delay Gate",
    boardCode: ";",
    defaultPrice: 3,
    palette: {
      order: 10,
      category: PaletteCategory.CircuitBasic,
      description: "Passes rear input to front output, one tick later. Use for delays and forcing direction.",
      extendedDescription: ["Passes -1, 0, and +1 unchanged with ordinary one-tick gate timing. A disconnected rear input produces 0. Has no side ports.", "Equivalent to a combiner rune with one input wired, or a delay rune with delay set to 1."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Up | WeldSide.Down,
    circuitInputPorts: WeldSide.Down,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#69727b",
    decorationStyle: TileDecorationStyle.DelayGate,
    decorationColor: "#d5e9f2",
  },
  [TileKind.Sensor]: {
    name: "Sensor Rune",
    boardCode: "S",
    defaultPrice: 10,
    palette: {
      order: 23,
      category: PaletteCategory.CircuitBasic,
      description: "Emits +1 when its pointed neighbor is occupied, except by glass.",
      extendedDescription: ["Checks only the cell immediately ahead and outputs 0 when it is empty or glass. The other three sides share the output."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#526875",
    decorationStyle: TileDecorationStyle.Sensor,
    decorationColor: "#9dcbe4",
  },
  [TileKind.FixedCharge]: {
    name: "Fixed Charge Rune",
    boardCode: "1",
    defaultPrice: 5,
    palette: {
      order: 12,
      category: PaletteCategory.CircuitBasic,
      description: "Emits +1 constantly into its welded circuit network.",
      extendedDescription: ["Connect it with welds to power a circuit. Multiple drivers combine by the sign of their sum, so an equal negative driver cancels this source."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#896321",
    decorationStyle: TileDecorationStyle.FixedCharge,
    decorationColor: "#f3dfa0",
  },
  [TileKind.Spark]: {
    name: "Spark Rune",
    boardCode: "K",
    defaultPrice: 3,
    palette: {
      order: 18,
      category: PaletteCategory.CircuitBasic,
      description: "Emits +1 for the first simulation tick, then goes dark.",
      extendedDescription: ["Use it to initialize a circuit or start a pulse sequence. Resetting the simulation lets it fire again; afterward it contributes 0 rather than holding +1."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#9a5128",
    decorationStyle: TileDecorationStyle.Spark,
    decorationColor: "#ffe3b0",
  },
  [TileKind.Inverter]: {
    name: "Inverter Rune",
    boardCode: "I",
    defaultPrice: 10,
    palette: {
      order: 13,
      category: PaletteCategory.CircuitGates,
      description: "Negates the sum of up to three isolated inputs.",
      extendedDescription: ["Reads the three non-pointed sides independently, adds their previous-tick charges, and negates the sign of the sum. Equal positive and negative inputs produce 0. The pointed side is the output."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#28587c",
    decorationStyle: TileDecorationStyle.Inverter,
    decorationColor: "#d2e9f5",
  },
  [TileKind.Combiner]: {
    name: "Combiner Rune",
    boardCode: "+",
    defaultPrice: 10,
    palette: {
      order: 14,
      category: PaletteCategory.CircuitGates,
      description: "Sums up to three isolated inputs toward its output.",
      extendedDescription: ["Reads the three non-pointed sides independently and outputs the sign of their sum one tick later. Positive and negative inputs cancel; disconnected inputs contribute 0."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#246d70",
    decorationStyle: TileDecorationStyle.Combiner,
    decorationColor: "#d2f0df",
  },
  [TileKind.Rectifier]: {
    name: "Rectifier Rune",
    boardCode: "R",
    defaultPrice: 15,
    palette: {
      order: 15,
      category: PaletteCategory.CircuitGates,
      description: "Passes positive sums from up to three isolated inputs.",
      extendedDescription: ["Adds the previous-tick inputs on its three non-pointed sides. The pointed output is +1 only when the sum is positive; zero and negative sums output 0."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#28647b",
    decorationStyle: TileDecorationStyle.Rectifier,
    decorationColor: "#d2edf5",
  },
  [TileKind.Multiplier]: {
    name: "Multiplier Rune",
    boardCode: "*",
    defaultPrice: 10,
    palette: {
      order: 16,
      category: PaletteCategory.CircuitGates,
      description: "Multiplies up to three connected isolated inputs.",
      extendedDescription: ["Multiplies connected previous-tick inputs and outputs toward the point. A connected 0 makes the product 0; disconnected sides are ignored. With no connected inputs it outputs +1."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#315b89",
    decorationStyle: TileDecorationStyle.Multiplier,
    decorationColor: "#d4e4f5",
  },
  [TileKind.Subtractor]: {
    name: "Subtractor Rune",
    boardCode: "-",
    defaultPrice: 15,
    palette: {
      order: 17,
      category: PaletteCategory.CircuitGates,
      description: "Subtracts left and right inputs from the rear input.",
      extendedDescription: ["The pointed output is the sign of rear minus left minus right, using previous-tick inputs. Missing inputs count as 0."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#2b727e",
    decorationStyle: TileDecorationStyle.Subtractor,
    decorationColor: "#d2edf5",
  },
  [TileKind.ChargeSensor]: {
    name: "Charge Sensor Rune",
    boardCode: "Q",
    defaultPrice: 15,
    palette: {
      order: 68,
      category: PaletteCategory.CircuitBasic,
      description: "Copies the charge of the tile side ahead to three isolated outputs.",
      extendedDescription: ["Looks straight ahead through empty space and glass, and reads the first block's near-side previous-tick charge. Its other three sides output that charge. Any block stops the scan, except glass; non-circuit blocks and an empty line to the board edge read 0. At a rune array's edge-center port, sensing continues outside the array."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.Up,
    circuitOutputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    magnetic: false,
    attractionRange: 0,
    fill: "#754291",
    decorationStyle: TileDecorationStyle.ChargeSensor,
    decorationColor: "#ead3ff",
  },
  [TileKind.MovementSensor]: {
    name: "Movement Sensor Rune",
    boardCode: "M",
    defaultPrice: 10,
    palette: {
      order: 71,
      category: PaletteCategory.CircuitBasic,
      description: "Reports the previous tick's net movement through four isolated outputs.",
      extendedDescription: ["Each axis outputs +1 toward the previous tick's net cell displacement and -1 on the opposite side. Diagonal movement activates both axes; an unchanged axis outputs 0. Stationary sensors output 0 on every side.", "Measures the net displacement across all movement phases, not intermediate moves or distance traveled. The first tick and newly produced sensors have no prior movement to report.", "Can fall and be welded on all four sides. No rotation is needed. Inside a rune array, it measures movement within that board; moving the containing array alone does not trigger it."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.All,
    magnetic: false,
    attractionRange: 0,
    fill: "#68428c",
    decorationStyle: TileDecorationStyle.MovementSensor,
    decorationColor: "#e2d2ff",
  },
  [TileKind.Selector]: {
    usesMirroring: true,
    name: "Selector Rune",
    boardCode: "T",
    defaultPrice: 10,
    palette: {
      order: 19,
      category: PaletteCategory.CircuitGates,
      description: "Selects the left or right input from the rear charge.",
      extendedDescription: ["A previous-tick rear input of +1 selects the left input; -1 selects the right. Rear 0 outputs 0. The pointed side outputs the selected previous-tick value."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#327589",
    decorationStyle: TileDecorationStyle.Selector,
    decorationColor: "#d6f1f5",
  },
  [TileKind.Equality]: {
    name: "Equality Rune",
    boardCode: "e",
    defaultPrice: 10,
    palette: {
      order: 20,
      category: PaletteCategory.CircuitGates,
      description: "Outputs +1 when all connected isolated inputs are equal.",
      extendedDescription: ["Compares only connected previous-tick inputs. All equal gives +1, otherwise 0; a connected neutral input participates. Zero or one connected input always gives +1."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#365f85",
    decorationStyle: TileDecorationStyle.Equality,
    decorationColor: "#d4e4f5",
  },
  [TileKind.Minimum]: {
    name: "Minimum Rune",
    boardCode: "<",
    defaultPrice: 10,
    palette: {
      order: 21,
      category: PaletteCategory.CircuitGates,
      description: "Outputs the minimum charge among its connected isolated inputs.",
      extendedDescription: ["The pointed output is the smallest connected previous-tick input: -1 before 0 before +1. Disconnected inputs are ignored; with none connected it outputs +1."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#245e76",
    decorationStyle: TileDecorationStyle.Minimum,
    decorationColor: "#d1edf0",
  },
  [TileKind.Maximum]: {
    name: "Maximum Rune",
    boardCode: ">",
    defaultPrice: 10,
    palette: {
      order: 22,
      category: PaletteCategory.CircuitGates,
      description: "Outputs the maximum charge among its connected isolated inputs.",
      extendedDescription: ["The pointed output is the largest connected previous-tick input: +1 before 0 before -1. Disconnected inputs are ignored; with none connected it outputs -1."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#287b82",
    decorationStyle: TileDecorationStyle.Maximum,
    decorationColor: "#d1edf0",
  },
  [TileKind.WireCrossing]: {
    name: "Crossing Rune",
    boardCode: "W",
    defaultPrice: 10,
    palette: {
      order: 11,
      category: PaletteCategory.CircuitBasic,
      description: "Keeps horizontal and vertical conduits separate.",
      extendedDescription: ["Opposite sides share charge, but perpendicular sides never connect electrically. Mechanical welds still join the crossing to its neighbors as a rigid body."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#526875",
    decorationStyle: TileDecorationStyle.WireCrossing,
    decorationColor: "#d5e9f2",
  },
  [TileKind.Glass]: {
    name: "Glass",
    boardCode: "G",
    defaultPrice: 3,
    palette: {
      order: 45,
      category: PaletteCategory.RawMaterials,
      description: "Solid block baked from sand. Invisible to sensor runes.",
      extendedDescription: ["Collides, falls, and welds like a solid block. Without welds, shatters when it stops after falling more than one cell. One-cell drops are safe; welding protects it and clears its fall history.", "An occupancy sensor facing glass reports 0; charge sensors look through it."],
    },
    affectedByGravity: true,
    invisibleToSensor: true,
    fragile: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#243d46",
    decorationStyle: TileDecorationStyle.Glass,
    decorationColor: "#d5f5f6",
  },
  [TileKind.IronOre]: {
    name: "Iron Ore",
    boardCode: "O",
    defaultPrice: 2,
    palette: {
      order: 46,
      category: PaletteCategory.RawMaterials,
      description: "Solid ore that a furnace smelts into iron.",
      extendedDescription: ["A furnace facing the ore transforms it into iron after six active ticks. Iron is magnetic; unprocessed iron ore is not."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#785a49",
    decorationStyle: TileDecorationStyle.SquareGrains,
    decorationColor: "#b7bdc5",
  },
  [TileKind.Dirt]: {
    name: "Dirt",
    boardCode: "d",
    defaultPrice: 1,
    palette: {
      order: 40,
      category: PaletteCategory.RawMaterials,
      description: "Solid dirt block affected by gravity; can be welded.",
      extendedDescription: ["Falls one cell per tick when unsupported and can be welded into a rigid body. This material is nonmagnetic and does not conduct circuit charge."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#765035",
    decorationStyle: TileDecorationStyle.Grains,
    decorationColor: "#a78052",
  },
  [TileKind.Gold]: {
    name: "Gold",
    boardCode: "h",
    defaultPrice: 6,
    palette: {
      order: 51,
      category: PaletteCategory.RawMaterials,
      description: "Solid gold block affected by gravity; can be welded.",
      extendedDescription: ["Falls one cell per tick when unsupported and can be welded into a rigid body. This material is nonmagnetic and does not conduct circuit charge."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#c99b32",
    decorationStyle: TileDecorationStyle.Iron,
    decorationColor: "#ffe8a1",
  },
  [TileKind.Silver]: {
    name: "Silver",
    boardCode: "s",
    defaultPrice: 5,
    palette: {
      order: 50,
      category: PaletteCategory.RawMaterials,
      description: "Solid silver block affected by gravity; can be welded.",
      extendedDescription: ["Falls one cell per tick when unsupported and can be welded into a rigid body. This material is nonmagnetic and does not conduct circuit charge."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#a7adb8",
    decorationStyle: TileDecorationStyle.Iron,
    decorationColor: "#f1f3ff",
  },
  [TileKind.Ruby]: {
    name: "Ruby",
    boardCode: "u",
    defaultPrice: 10,
    palette: {
      order: 53,
      category: PaletteCategory.RawMaterials,
      description: "Solid ruby block affected by gravity; can be welded.",
      extendedDescription: ["Falls one cell per tick when unsupported and can be welded into a rigid body. This material is nonmagnetic and does not conduct circuit charge."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#a11b41",
    decorationStyle: TileDecorationStyle.Gem,
    decorationColor: "#ffb1bc",
  },
  [TileKind.Sapphire]: {
    name: "Sapphire",
    boardCode: "v",
    defaultPrice: 10,
    palette: {
      order: 54,
      category: PaletteCategory.RawMaterials,
      description: "Solid sapphire block affected by gravity; can be welded.",
      extendedDescription: ["Falls one cell per tick when unsupported and can be welded into a rigid body. This material is nonmagnetic and does not conduct circuit charge."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#1c3a8d",
    decorationStyle: TileDecorationStyle.Gem,
    decorationColor: "#a8ceff",
  },
  [TileKind.Emerald]: {
    name: "Emerald",
    boardCode: "j",
    defaultPrice: 10,
    palette: {
      order: 55,
      category: PaletteCategory.RawMaterials,
      description: "Solid emerald block affected by gravity; can be welded.",
      extendedDescription: ["Falls one cell per tick when unsupported and can be welded into a rigid body. This material is nonmagnetic and does not conduct circuit charge."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#0f6a35",
    decorationStyle: TileDecorationStyle.Gem,
    decorationColor: "#a0f2c0",
  },
  [TileKind.Diamond]: {
    name: "Diamond",
    boardCode: "q",
    defaultPrice: 20,
    palette: {
      order: 57,
      category: PaletteCategory.RawMaterials,
      description: "Solid diamond block affected by gravity; can be welded.",
      extendedDescription: ["Falls one cell per tick when unsupported and can be welded into a rigid body. This material is nonmagnetic and does not conduct circuit charge."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#a6d8df",
    decorationStyle: TileDecorationStyle.Gem,
    decorationColor: "#f4ffff",
  },
  [TileKind.Amethyst]: {
    name: "Amethyst",
    boardCode: "t",
    defaultPrice: 10,
    palette: {
      order: 56,
      category: PaletteCategory.RawMaterials,
      description: "Solid amethyst block affected by gravity; can be welded.",
      extendedDescription: ["Falls one cell per tick when unsupported and can be welded into a rigid body. This material is nonmagnetic and does not conduct circuit charge."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#791daf",
    decorationStyle: TileDecorationStyle.Gem,
    decorationColor: "#eac0ff",
  },
  [TileKind.Mithril]: {
    name: "Mithril",
    boardCode: "l",
    defaultPrice: 10,
    palette: {
      order: 52,
      category: PaletteCategory.RawMaterials,
      description: "Solid mithril block affected by gravity; can be welded.",
      extendedDescription: ["Falls one cell per tick when unsupported and can be welded into a rigid body. This material is nonmagnetic and does not conduct circuit charge."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#0c44a5",
    decorationStyle: TileDecorationStyle.Iron,
    decorationColor: "#ffffff",
  },
  [TileKind.CopperOre]: {
    name: "Copper Ore",
    boardCode: "o",
    defaultPrice: 2,
    palette: {
      order: 48,
      category: PaletteCategory.RawMaterials,
      description: "Solid copper ore block affected by gravity; can be welded.",
      extendedDescription: ["Falls one cell per tick when unsupported and can be welded into a rigid body. This material is nonmagnetic and does not conduct circuit charge.", "A furnace turns copper ore into copper in six active ticks while wood touches any orthogonal side of the ore. Wood is not consumed; removing it pauses progress."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#535c50",
    decorationStyle: TileDecorationStyle.SquareGrains,
    decorationColor: "#df9360",
  },
  [TileKind.Copper]: {
    name: "Copper",
    boardCode: "c",
    defaultPrice: 4,
    palette: {
      order: 49,
      category: PaletteCategory.RawMaterials,
      description: "Solid copper block affected by gravity; can be welded.",
      extendedDescription: ["Falls one cell per tick when unsupported and can be welded into a rigid body. This material is nonmagnetic and does not conduct circuit charge."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#b66d44",
    decorationStyle: TileDecorationStyle.Iron,
    decorationColor: "#f6c398",
  },
  [TileKind.Wood]: {
    name: "Wood",
    boardCode: "w",
    defaultPrice: 1,
    palette: {
      order: 42,
      category: PaletteCategory.RawMaterials,
      description: "Solid wood block affected by gravity; can be welded.",
      extendedDescription: ["Falls one cell per tick when unsupported and can be welded into a rigid body. This material is nonmagnetic and does not conduct circuit charge."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#55391f",
    decorationStyle: TileDecorationStyle.Wood,
    decorationColor: "#9a703f",
  },
  [TileKind.Drill]: {
    name: "Drill",
    boardCode: "f",
    defaultPrice: 15,
    palette: {
      order: 7,
      category: PaletteCategory.Transformation,
      description: "Breaks the block ahead in four active ticks; side -1 pauses it; rear outputs +1 while drilling.",
      extendedDescription: ["Reads the previous-tick shared side charge: -1 pauses drilling; 0 or +1 enables it. Progress follows the target's identity; changing targets resets it. Removes one tile and its welds, not the rest of its welded body. The pointed side cannot be welded.", "The isolated rear output is +1 on every active drilling tick, including completion. Targets start-of-tick blocks, before movement. Multiple active drills targeting the same block jam and pause progress. Cannot destroy indestructible blocks such as platforms; produces no material."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: true,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.Down,
    magnetic: false,
    attractionRange: 0,
    fill: "#59616b",
    decorationStyle: TileDecorationStyle.Drill,
    decorationColor: "#efd0a1",
  },
  [TileKind.Furnace]: {
    name: "Furnace",
    boardCode: "F",
    defaultPrice: 15,
    palette: {
      order: 60,
      category: PaletteCategory.Transformation,
      description: "Bakes the block on its pointed side; linked side -1 pauses it; rear outputs +1 while baking.",
      extendedDescription: ["Sand becomes glass in four active ticks; iron ore becomes iron in six. Copper ore becomes copper in six active ticks while wood touches an orthogonal side of the ore; the wood is not consumed, and removing it pauses progress. A -1 on the shared side circuit also pauses progress; 0 or +1 allows cooking.", "Freshly cooked glass welds to adjacent existing glass, but not to sand cooked in the same tick. Metal smelting adds no welds.", "The isolated rear output is +1 on every active baking tick, including completion. Moving a different target in front resets progress."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.Down,
    magnetic: false,
    attractionRange: 0,
    fill: "#6b5042",
    decorationStyle: TileDecorationStyle.Furnace,
    decorationColor: "#f0b25c",
  },
  [TileKind.Grinder]: {
    name: "Grinder",
    boardCode: "k",
    defaultPrice: 15,
    palette: {
      order: 75,
      category: PaletteCategory.Transformation,
      description: "Grinds the block on its pointed side; linked side -1 pauses it; rear outputs +1 while grinding.",
      extendedDescription: ["Stone and glass become sand after four active ticks. A -1 on the shared side circuit pauses progress; 0 or +1 allows grinding.", "The resulting sand cannot be welded, so grinding removes the target's welds.", "The isolated rear output is +1 on every active grinding tick, including completion. Moving a different target in front resets progress."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.Down,
    magnetic: false,
    attractionRange: 0,
    fill: "#53615c",
    decorationStyle: TileDecorationStyle.Grinder,
    decorationColor: "#d2d7bd",
  },
  [TileKind.Conveyor]: {
    usesMirroring: true,
    name: "Conveyor Belt",
    boardCode: "B",
    defaultPrice: 5,
    palette: {
      order: 3,
      category: PaletteCategory.Motion,
      description: "Charged roller: +1 clockwise, -1 counterclockwise, 0 stopped.",
      extendedDescription: ["Moves unwelded neighbors tangentially and applies the opposite reaction to its own body. Cannot move bodies upwards against gravity. Blocked motion can push other movable bodies.", "Press M to place mirrored. Mirroring reverses the roller: +1 counterclockwise, -1 clockwise. Mirrored belts show counterclockwise chevrons."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#59636b",
    decorationStyle: TileDecorationStyle.Conveyor,
    decorationColor: "#d6c38b",
  },
  [TileKind.Delivery]: {
    name: "Delivery Box",
    boardCode: "D",
    defaultPrice: 10,
    palette: {
      order: 43,
      category: PaletteCategory.PuzzleTools,
      description: "Absorbs a front welded body exactly matching the body behind it and pulses +1 sideways. Indestructible and weld-protected.",
      extendedDescription: ["Matches complete bodies by tile kinds, directional orientations, and weld layout, allowing translation but not rotation or reflection. Configuration does not affect the match.", "The rear body remains as the template. Bodies welded to the box do not match; competing consumption claims jam rather than consuming only part of a body.", "Cannot be destroyed by drills, or welded/split on sides shared with other weld-protected blocks."],
    },
    affectedByGravity: true,
    indestructible: true,
    runtimeWeldProtected: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#66513d",
    decorationStyle: TileDecorationStyle.Delivery,
    decorationColor: "#e8c987",
  },
  [TileKind.Comparer]: {
    name: "Body Comparer",
    boardCode: "?",
    defaultPrice: 15,
    palette: {
      order: 63,
      category: PaletteCategory.CircuitComplex,
      description: "Outputs +1 sideways while the complete front and rear bodies match in kinds, orientations, and welds; ignores configuration and consumes nothing.",
      extendedDescription: ["Uses the same translation-only body comparison as a delivery box. Both neighbors must exist and neither body may be welded to the comparer. A mismatch outputs 0; matching does not consume either body."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#635078",
    decorationStyle: TileDecorationStyle.Comparer,
    decorationColor: "#e8c987",
  },
  [TileKind.BlockComparer]: {
    name: "Block Type Comparer",
    boardCode: "@",
    defaultPrice: 10,
    palette: {
      order: 72,
      category: PaletteCategory.CircuitComplex,
      description: "Outputs +1 sideways while the front and rear blocks have the same type; consumes nothing.",
      extendedDescription: ["Both neighboring cells must contain blocks. Compares only their types, ignoring orientation, configuration, and welds, even when welded to the comparer. Different types or missing neighbors output 0."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#4e647e",
    decorationStyle: TileDecorationStyle.Comparer,
    decorationColor: "#c7e3f5",
  },
  [TileKind.BeamBlockSensor]: {
    name: "Beam Block Sensor",
    boardCode: "3",
    defaultPrice: 15,
    palette: {
      order: 77,
      category: PaletteCategory.CircuitComplex,
      description: "Counts matching blocks ahead and outputs −1, 0, or +1 sideways below, at, or above its threshold. Press E to configure.",
      extendedDescription: ["Scans every cell from one cell ahead to this board's boundary, through gaps and other blocks. By default, counts blocks with the immediate rear block's type, including glass, ignoring orientation, configuration, and welds. A missing rear block gives a count of zero.", "Press E to set a threshold from 0 to 120000 or enable Match all to count every nonempty forward-ray cell without using a rear template. Outputs −1 below the threshold, 0 at it, and +1 above it. The default threshold is 0 and Match all is off. Consumes nothing; beams never leave their board or rune array."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#4e647e",
    decorationStyle: TileDecorationStyle.BeamBlockSensor,
    decorationColor: "#c7e3f5",
  },
  [TileKind.BeamBodySensor]: {
    name: "Beam Body Sensor",
    boardCode: "4",
    defaultPrice: 20,
    palette: {
      order: 76,
      category: PaletteCategory.CircuitComplex,
      description: "Counts distinct matching bodies ahead and outputs −1, 0, or +1 sideways below, at, or above its threshold. Press E to configure.",
      extendedDescription: ["Scans from one cell ahead to this board's boundary, through gaps and other bodies, counting each distinct welded body intersecting the ray once. By default, compares against the complete immediate rear body using the Body Comparer's translation-only matching of kinds, orientations, handedness, and welds, ignoring configuration. Missing rear bodies and bodies joined to the sensor do not match.", "Press E to set a threshold from 0 to 120000 or enable Match all to count every distinct nonempty body intersecting the ray, including the sensor's own body, without using a rear template. Outputs −1 below the threshold, 0 at it, and +1 above it. The default threshold is 0 and Match all is off. Consumes nothing; beams never leave their board or rune array."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#635078",
    decorationStyle: TileDecorationStyle.BeamBlockSensor,
    decorationColor: "#e8c987",
  },
  [TileKind.Victory]: {
    name: "Judgment Stone",
    boardCode: "V",
    defaultPrice: 10000,
    palette: {
      order: 24,
      category: PaletteCategory.PuzzleTools,
      description: "Wins on +1 input or loses on -1 input; opposing inputs jam. Indestructible and weld-protected.",
      extendedDescription: ["The result latches once triggered. In a puzzle, manual steps do not record completion: the full test must succeed on every case. A victory block inside a rune array affects the whole puzzle. Cannot be destroyed by drills, or welded/split at sides shared with other weld-protected blocks."],
    },
    affectedByGravity: true,
    indestructible: true,
    runtimeWeldProtected: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.All,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#633a85",
    decorationStyle: TileDecorationStyle.Victory,
    decorationColor: "#eadb88",
  },
  [TileKind.Delay]: {
    name: "Delay Rune",
    boardCode: "Z",
    defaultPrice: 30,
    palette: {
      order: 36,
      category: PaletteCategory.CircuitComplex,
      description: "Delays the isolated rear input by a configurable number of ticks. Press E or shift + mousewheel to configure.",
      extendedDescription: ["Each tick outputs the oldest queued value, then stores the rear input, including 0. The queue starts neutral. Change the delay by pressing E or shift + mousewheel."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Up | WeldSide.Down,
    circuitInputPorts: WeldSide.Down,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#3c568c",
    decorationStyle: TileDecorationStyle.Delay,
    decorationColor: "#d3e3f2",
  },
  [TileKind.Discard]: {
    name: "Discard Rune",
    boardCode: "n",
    defaultPrice: 20,
    palette: {
      order: 39,
      category: PaletteCategory.CircuitComplex,
      description: "Discards the first N rear-input ticks, then passes the rest through. Press E or shift + mousewheel to configure.",
      extendedDescription: ["Outputs 0 for the first N ticks. Afterward, copies the rear input to the isolated front output with a 1-tick delay. Configure N from 0 to 99 by pressing E or shift + mousewheel."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Up | WeldSide.Down,
    circuitInputPorts: WeldSide.Down,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#435087",
    decorationStyle: TileDecorationStyle.Discard,
    decorationColor: "#dce3f7",
  },
  [TileKind.Counter]: {
    name: "Counter Rune",
    boardCode: "N",
    defaultPrice: 20,
    palette: {
      order: 37,
      category: PaletteCategory.CircuitComplex,
      description: "Adds signed rear inputs and pulses with the wrap direction. Press E or shift + mousewheel to configure.",
      extendedDescription: ["Adds the rear charge to its stored count each tick. Crossing the configured threshold wraps the count and emits +1; wrapping backward emits -1. Other ticks output 0. Configure by pressing E or shift + mousewheel."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Up | WeldSide.Down,
    circuitInputPorts: WeldSide.Down,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#55418d",
    decorationStyle: TileDecorationStyle.Counter,
    decorationColor: "#eadcf7",
  },
  [TileKind.Rom]: {
    usesMirroring: true,
    name: "Lore Rune",
    boardCode: "U",
    defaultPrice: 30,
    palette: {
      order: 29,
      category: PaletteCategory.CircuitComplex,
      description: "Read-only memory. Positive inputs move the 2D cursor away from their side; negative inputs reverse it. Outputs the selected value. Press E to configure.",
      extendedDescription: ["With the unmirrored rune pointing up, +1 on the left moves right and +1 at the rear moves up; -1 reverses each movement. Both inputs can move the cursor in one tick, local-left input before rear input.", "By default, horizontal movement wraps into the next or previous row; vertical movement wraps into the next or previous column. These carry directions rotate and reflect with the rune. Passing the final cell wraps around the whole memory. E edits the spatial grid and toggles horizontal and vertical wrapping separately. A move is ignored if it or its carry would cross a disabled edge. Front and local-right output the value after movement."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Left | WeldSide.Down,
    circuitOutputPorts: WeldSide.Up | WeldSide.Right,
    magnetic: false,
    attractionRange: 0,
    fill: "#23775d",
    decorationStyle: TileDecorationStyle.Rom,
    decorationColor: "#d1ece1",
  },
  [TileKind.Lut]: {
    usesMirroring: true,
    name: "Lookup Rune",
    boardCode: "p",
    defaultPrice: 20,
    palette: {
      order: 35,
      category: PaletteCategory.CircuitComplex,
      description: "Looks up two ternary inputs in an editable 3 by 3 table. Front and right output the same value. Press E to configure.",
      extendedDescription: ["The previous-tick left input selects the column and the rear input selects the row. Both axes run -1, 0, +1: columns left to right and rows top to bottom. Disconnected inputs count as 0.", "Both isolated outputs drive the selected value with ordinary rune timing. The fixed table has no cursor, does not change when rotated or reflected, and cannot be displayed by a Lore Grapher."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Left | WeldSide.Down,
    circuitOutputPorts: WeldSide.Up | WeldSide.Right,
    magnetic: false,
    attractionRange: 0,
    fill: "#176f75",
    decorationStyle: TileDecorationStyle.Lut,
    decorationColor: "#c9f4e6",
  },
  [TileKind.Welder]: {
    name: "Welder",
    boardCode: "J",
    defaultPrice: 10,
    palette: {
      order: 30,
      category: PaletteCategory.Transformation,
      description: "Welds both transverse edges of the block ahead; -1 side charge disables it.",
      extendedDescription: ["For an upward-facing welder, joins the left and right edges of the cell ahead when both adjacent tiles permit welds. Shared side -1 disables it; the isolated rear output pulses +1 only when a weld changes.", "Cannot weld together two weld-protected blocks, such as platforms, delivery blocks, or judgment stones."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: true,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.Down,
    magnetic: false,
    attractionRange: 0,
    fill: "#6d5c4b",
    decorationStyle: TileDecorationStyle.Welder,
    decorationColor: "#f0b85d",
  },
  [TileKind.Splitter]: {
    name: "Splitter",
    boardCode: "X",
    defaultPrice: 10,
    palette: {
      order: 31,
      category: PaletteCategory.Transformation,
      description: "Splits both transverse edges of the block ahead; -1 side charge disables it.",
      extendedDescription: ["For an upward-facing splitter, removes the left and right welds of the cell ahead. Shared side -1 disables it; the isolated rear output pulses +1 only when a weld changes. Opposing weld and split commands on one edge jam.", "Cannot weld together two weld-protected blocks, such as platforms, delivery blocks, or judgment stones."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: true,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.Down,
    magnetic: false,
    attractionRange: 0,
    fill: "#625669",
    decorationStyle: TileDecorationStyle.Splitter,
    decorationColor: "#e0b7ee",
  },
  [TileKind.Dismantler]: {
    name: "Dismantler",
    boardCode: "2",
    defaultPrice: 15,
    palette: {
      order: 33,
      category: PaletteCategory.Transformation,
      description: "Removes all four welds of the block ahead; -1 side charge disables it.",
      extendedDescription: ["Removes every weld around the cell ahead, including a weld to the dismantler itself. Shared side -1 disables it; the isolated rear output pulses +1 only when a weld changes. Opposing welder commands jam only the contested edges.", "Cannot cut an edge between two weld-protected blocks, such as platforms, delivery blocks, or judgment stones."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.Down,
    magnetic: false,
    attractionRange: 0,
    fill: "#705064",
    decorationStyle: TileDecorationStyle.Dismantler,
    decorationColor: "#f4bdd5",
  },
  [TileKind.LaserSplitter]: {
    usesMirroring: true,
    name: "Laser Splitter",
    boardCode: "x",
    defaultPrice: 15,
    palette: {
      order: 32,
      category: PaletteCategory.Transformation,
      description: "Cuts the left edge of every cell ahead, through blocks and gaps; -1 side charge disables it.",
      extendedDescription: ["Cuts one straight line of welds to the board boundary. For an upward-facing laser splitter, cuts the left edge of every cell above it, starting with the cell immediately ahead; rotate to change the cutting side.", "The beam passes through blocks and empty cells without destroying tiles. Shared side -1 disables it; the isolated rear output pulses +1 only when at least one weld changes. Opposing welder commands jam only the contested edges.", "Can be mirrored with the M key.", "Cannot weld together two weld-protected blocks, such as platforms, delivery blocks, or judgment stones."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: true,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.Down,
    magnetic: false,
    attractionRange: 0,
    fill: "#58436c",
    decorationStyle: TileDecorationStyle.LaserSplitter,
    decorationColor: "#f3a1e5",
  },
  [TileKind.Duplicator]: {
    name: "Duplicator",
    boardCode: "Y",
    defaultPrice: 30,
    palette: {
      order: 58,
      category: PaletteCategory.Transformation,
      description: "When given +1 side charge, creates a mirrored duplicate of the welded body behind it.",
      extendedDescription: ["Uses the previous-tick shared side charge. Every mirrored destination must be empty and inside the board; blocked or overlapping copies jam. Copies retain configuration and mirrored welds but get new tile IDs."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.Right | WeldSide.Left,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#58666c",
    decorationStyle: TileDecorationStyle.Duplicator,
    decorationColor: "#c9e4dc",
  },
  [TileKind.Monitor]: {
    name: "Signal Monitor",
    boardCode: "m",
    defaultPrice: 0,
    palette: {
      order: 27,
      category: PaletteCategory.CircuitComplex,
      description: "Joins its welded circuit like a conduit and records that charge every tick on the signal panel. Press E to name its line.",
      extendedDescription: ["Records committed tick values, not animation frames. E sets a label and category to group related traces. Moving a monitor preserves its trace; reset starts a new history."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#354f83",
    decorationStyle: TileDecorationStyle.Monitor,
    decorationColor: "#d8e4f4",
  },
  [TileKind.Grapher]: {
    name: "Lore Grapher",
    boardCode: "g",
    defaultPrice: 0,
    palette: {
      order: 28,
      category: PaletteCategory.CircuitComplex,
      description: "Shows every value of the ROM or sequence checker it points at on the signal panel, marking the cursor. Press E to name its line.",
      extendedDescription: ["Displays the complete stored grid rather than a time history. Point it directly at a ROM or sequence checker. E sets a label and category; nested-array traces also appear in the main signal panel."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#286d65",
    decorationStyle: TileDecorationStyle.Grapher,
    decorationColor: "#d6ecea",
  },
  [TileKind.Checker]: {
    name: "Sequence Checker",
    boardCode: "E",
    defaultPrice: 30,
    palette: {
      order: 74,
      category: PaletteCategory.PuzzleTools,
      description: "Waits for the first nonzero rear input, then compares each input with its stored sequence: +1 after a complete match, -1 at the first mismatch. Press E to configure.",
      extendedDescription: ["Expected values are read left to right, row by row. After starting, neutral inputs also count unless Ignore zero inputs is enabled; that mode requires an entirely nonzero expected sequence.", "Success and failure latch until reset. E edits the sequence and zero-handling option."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Up | WeldSide.Down,
    circuitInputPorts: WeldSide.Down,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#896326",
    decorationStyle: TileDecorationStyle.Checker,
    decorationColor: "#f2dea3",
  },
  [TileKind.RuneArray]: {
    name: "Rune Array",
    boardCode: "A",
    defaultPrice: 10,
    palette: {
      order: 62,
      category: PaletteCategory.CircuitComplex,
      description: "Holds a miniature board whose four edge-center cells connect to its sides with no delay. Press E to configure, Enter to open.",
      extendedDescription: ["The inner board runs ordinary physics and circuits, including gravity. Its four edge-center cells connect to independent outer sides without an extra circuit tick.", "E configures an odd-sized board up to 15 by 15; Enter opens it. Arrays can contain arrays. Puzzle solution price includes inner components, but footprint does not count internal space."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#3c438c",
    decorationStyle: TileDecorationStyle.RuneArray,
    decorationColor: "#c7d3f4",
  },
  [TileKind.Assembler]: {
    usesMirroring: true,
    name: "Assembler",
    boardCode: "H",
    defaultPrice: 15,
    palette: {
      order: 59,
      category: PaletteCategory.Transformation,
      description: "Consumes matching recipes ahead and emits products behind; left -1 pauses it, right pulses +1 on production.",
      extendedDescription: ["Consumes only a complete matching body in any rotation, then emits one unwelded product per tick behind it. While outputs are queued it accepts no new recipe; a blocked rear cell pauses emission without discarding the queue.", "A previous-tick -1 on the left circuit pauses both consumption and emission; 0 or +1 enables them. The isolated right output pulses +1 only when a product is emitted, not when a recipe is consumed or an output is blocked."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.Right | WeldSide.Left,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.Right,
    magnetic: false,
    attractionRange: 0,
    fill: "#5f5347",
    decorationStyle: TileDecorationStyle.Assembler,
    decorationColor: "#e2b96a",
  },
  [TileKind.Rotator]: {
    usesMirroring: true,
    name: "Rotator",
    boardCode: "r",
    defaultPrice: 15,
    palette: {
      order: 34,
      category: PaletteCategory.Motion,
      description: "Turns its gripped body 90° with +1 clockwise or -1 counterclockwise rear input.",
      extendedDescription: ["Grips ahead or to either side, never behind. If terrain, a boundary, or its own body blocks the gripped body's turn, it instead tries turning its own body the opposite way around the rotator cell, keeping the grip stationary. Turns carry swept bodies and enclosed loose contents, preserving orientations and welds. A blocked reaction or competing turns jam; competing turns do not trigger reaction."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.Down,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Down,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#5c5368",
    decorationStyle: TileDecorationStyle.Rotator,
    decorationColor: "#e1c3f2",
  },
  [TileKind.Piston]: {
    name: "Piston",
    boardCode: "P",
    defaultPrice: 10,
    palette: {
      order: 8,
      category: PaletteCategory.Motion,
      description: "Extends on +1 and retracts on -1; its pointed side is the arm head.",
      extendedDescription: ["Positive charge pushes forward; if the head is blocked, the base can recoil backward instead. Neutral holds the current extension. Negative charge retracts and pulls only a body welded to the head.", "Downward-facing pistons first try lowering the base onto the arm, keeping grounded feet in place. If the base cannot move down, they lift the head instead. Retraction never pushes unwelded obstructions."],
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#67584b",
    decorationStyle: TileDecorationStyle.Piston,
    decorationColor: "#d1aa6b",
  },
  [TileKind.PistonBase]: {
    name: "Piston Base",
    boardCode: "b",
    defaultPrice: 0,
    palette: null,
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#67584b",
    decorationStyle: TileDecorationStyle.PistonBase,
    decorationColor: "#d1aa6b",
  },
  [TileKind.PistonArm]: {
    name: "Piston Arm",
    boardCode: "a",
    defaultPrice: 0,
    palette: null,
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.Up | WeldSide.Down,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#8b755e",
    decorationStyle: TileDecorationStyle.PistonArm,
    decorationColor: "#e3c486",
  },
};

export const TILE_KINDS: readonly TileKind[] = Object.freeze(
  Object.keys(TILE_DEFINITIONS).map((value) => Number(value) as TileKind),
);

function buildTileKindsByBoardCode(): Readonly<Record<string, TileKind | undefined>> {
  const kindsByCode = Object.create(null) as Record<string, TileKind | undefined>;
  for (const kind of TILE_KINDS) {
    const definition = TILE_DEFINITIONS[kind];
    if (definition.boardCode.length !== 1) {
      throw new Error(`Board code for ${definition.name} must be one character`);
    }
    if (Object.hasOwn(kindsByCode, definition.boardCode)) {
      throw new Error(`Duplicate board tile code "${definition.boardCode}"`);
    }
    kindsByCode[definition.boardCode] = kind;
  }
  return kindsByCode;
}

const TILE_KINDS_BY_BOARD_CODE = buildTileKindsByBoardCode();

/** Tile kind for a compact board code, or undefined for an unknown code. */
export function tileKindForBoardCode(code: string): TileKind | undefined {
  return TILE_KINDS_BY_BOARD_CODE[code];
}

export function isTileKind(value: number): value is TileKind {
  return Number.isInteger(value) && Object.hasOwn(TILE_DEFINITIONS, value);
}

export function orientationForKind(kind: TileKind, orientation: Direction): Direction {
  return TILE_DEFINITIONS[kind].usesOrientation ? orientation : Direction.Up;
}

export function mirroringForKind(kind: TileKind, mirrored: boolean): boolean {
  return TILE_DEFINITIONS[kind].usesMirroring === true && mirrored;
}

/** Reflects a local direction, then rotates it into world coordinates. */
export function orientedDirection(
  direction: Direction,
  orientation: Direction,
  mirrored = false,
): Direction {
  return (((mirrored ? flipDirectionHorizontally(direction) : direction) + orientation) & 3) as Direction;
}

/** Reflects local left/right, then rotates an upward-facing side mask. */
export function orientedSides(sides: WeldSide, orientation: Direction, mirrored = false): WeldSide {
  if (mirrored) {
    sides = ((sides & (WeldSide.Up | WeldSide.Down)) |
      ((sides & WeldSide.Left) >> 2) | ((sides & WeldSide.Right) << 2)) as WeldSide;
  }
  return (
    ((sides << orientation) | (sides >> (4 - orientation))) &
    WeldSide.All
  ) as WeldSide;
}
