export const enum TileKind {
  Empty = 0,
  Stone = 1,
  Sand = 2,
  Platform = 3,
  Magnet = 4,
  Iron = 5,
  Conduit = 6,
  Sensor = 7,
  Inverter = 8,
  Combiner = 9,
  Rectifier = 10,
  Multiplier = 11,
  Subtractor = 12,
  ChargeSensor = 13,
  Selector = 14,
  WireCrossing = 15,
  Glass = 16,
  IronOre = 17,
  Furnace = 18,
  Conveyor = 19,
  Delivery = 20,
  Victory = 21,
  FixedCharge = 22,
  Spark = 23,
  Piston = 24,
  PistonBase = 25,
  PistonArm = 26,
  Delay = 27,
  Counter = 28,
  Rom = 29,
  Welder = 30,
  Splitter = 31,
  Duplicator = 32,
  Monitor = 33,
  Grapher = 34,
  Checker = 35,
  RuneArray = 36,
  Assembler = 37,
  Equality = 38,
  Minimum = 39,
  Maximum = 40,
  Rotator = 41,
}

export const enum Direction {
  Up = 0,
  Right = 1,
  Down = 2,
  Left = 3,
}

export const enum WeldSide {
  None = 0,
  Up = 1 << Direction.Up,
  Right = 1 << Direction.Right,
  Down = 1 << Direction.Down,
  Left = 1 << Direction.Left,
  All = Up | Right | Down | Left,
}

export const enum TileDecorationStyle {
  None = 0,
  Crack = 1,
  Grains = 2,
  Magnet = 3,
  Iron = 4,
  Conduit = 5,
  Sensor = 6,
  Inverter = 7,
  Combiner = 8,
  Rectifier = 9,
  Multiplier = 10,
  Subtractor = 11,
  ChargeSensor = 12,
  Selector = 13,
  WireCrossing = 14,
  Furnace = 15,
  Conveyor = 16,
  Delivery = 17,
  Victory = 18,
  FixedCharge = 19,
  Spark = 20,
  Piston = 21,
  PistonBase = 22,
  PistonArm = 23,
  Delay = 24,
  Counter = 25,
  Rom = 26,
  Welder = 27,
  Splitter = 28,
  Duplicator = 29,
  Monitor = 30,
  Grapher = 31,
  Checker = 32,
  RuneArray = 33,
  Assembler = 34,
  Equality = 35,
  Minimum = 36,
  Maximum = 37,
  Rotator = 38,
}

export const enum PaletteCategory {
  RawMaterials = 0,
  Mechanisms = 1,
  Circuits = 2,
  PuzzleTools = 3,
}

export interface TileDefinition {
  readonly name: string;
  /** Single UTF-16 code unit used by the compact board format. */
  readonly boardCode: string;
  /** Sandbox component-palette presentation. Empty tiles are not palette entries. */
  readonly palette: {
    readonly order: number;
    readonly category: PaletteCategory;
    readonly description: string;
  } | null;
  readonly affectedByGravity: boolean;
  readonly weldableSides: WeldSide;
  readonly excludesFacingWeld: boolean;
  readonly usesOrientation: boolean;
  readonly circuitPorts: WeldSide;
  /** Isolated input or sensing ports relative to an upward-facing tile. */
  readonly circuitInputPorts: WeldSide;
  /** Isolated output ports relative to an upward-facing tile. */
  readonly circuitOutputPorts: WeldSide;
  readonly slidesDiagonally: boolean;
  readonly magnetic: boolean;
  readonly attractionRange: number;
  readonly fill: string;
  readonly shadow: string;
  readonly decorationStyle: TileDecorationStyle;
  readonly decorationColor: string;
}

export function directionX(direction: Direction): -1 | 0 | 1 {
  return direction === Direction.Right ? 1 : direction === Direction.Left ? -1 : 0;
}

export function directionY(direction: Direction): -1 | 0 | 1 {
  return direction === Direction.Down ? 1 : direction === Direction.Up ? -1 : 0;
}

export function oppositeDirection(direction: Direction): Direction {
  return ((direction + 2) & 3) as Direction;
}

export function flipDirectionHorizontally(direction: Direction): Direction {
  if (direction === Direction.Right) {
    return Direction.Left;
  }
  if (direction === Direction.Left) {
    return Direction.Right;
  }
  return direction;
}

export function flipDirectionVertically(direction: Direction): Direction {
  if (direction === Direction.Up) {
    return Direction.Down;
  }
  if (direction === Direction.Down) {
    return Direction.Up;
  }
  return direction;
}

export const TILE_DEFINITIONS: Readonly<Record<TileKind, TileDefinition>> = {
  [TileKind.Empty]: {
    name: "Empty",
    boardCode: ".",
    palette: null,
    affectedByGravity: false,
    slidesDiagonally: false,
    weldableSides: WeldSide.None,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "transparent",
    shadow: "transparent",
    decorationStyle: TileDecorationStyle.None,
    decorationColor: "transparent",
  },
  [TileKind.Stone]: {
    name: "Stone",
    boardCode: "#",
    palette: {
      order: 1,
      category: PaletteCategory.RawMaterials,
      description: "Solid block affected by gravity",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#66717d",
    shadow: "#3c454f",
    decorationStyle: TileDecorationStyle.Crack,
    decorationColor: "#525d68",
  },
  [TileKind.Sand]: {
    name: "Sand",
    boardCode: ":",
    palette: {
      order: 0,
      category: PaletteCategory.RawMaterials,
      description: "Falls downward and can fall diagonally around obstacles",
    },
    affectedByGravity: true,
    slidesDiagonally: true,
    weldableSides: WeldSide.None,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#e7ad4f",
    shadow: "#a86d2b",
    decorationStyle: TileDecorationStyle.Grains,
    decorationColor: "#8d5b26",
  },
  [TileKind.Platform]: {
    name: "Platform",
    boardCode: "=",
    palette: {
      order: 2,
      category: PaletteCategory.RawMaterials,
      description: "Fixed structural block not affected by gravity",
    },
    affectedByGravity: false,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#56736b",
    shadow: "#30473f",
    decorationStyle: TileDecorationStyle.Crack,
    decorationColor: "#405b52",
  },
  [TileKind.Magnet]: {
    name: "Magnet",
    boardCode: "L",
    palette: {
      order: 3,
      category: PaletteCategory.Mechanisms,
      description: "Holds magnetic blocks on its pointed side",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: true,
    usesOrientation: true,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 1,
    fill: "#b94b52",
    shadow: "#6e2930",
    decorationStyle: TileDecorationStyle.Magnet,
    decorationColor: "#f3e5c8",
  },
  [TileKind.Iron]: {
    name: "Iron",
    boardCode: "i",
    palette: {
      order: 4,
      category: PaletteCategory.RawMaterials,
      description: "Magnetic structural block affected by gravity and smelted from iron ore",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: true,
    attractionRange: 0,
    fill: "#718a9b",
    shadow: "#405767",
    decorationStyle: TileDecorationStyle.Iron,
    decorationColor: "#d5e1e7",
  },
  [TileKind.Conduit]: {
    name: "Conduit",
    boardCode: "C",
    palette: {
      order: 9,
      category: PaletteCategory.Circuits,
      description: "Shares charge across welded circuit blocks",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#69727b",
    shadow: "#3b4249",
    decorationStyle: TileDecorationStyle.Conduit,
    decorationColor: "#162f4b",
  },
  [TileKind.Sensor]: {
    name: "Sensor Rune",
    boardCode: "S",
    palette: {
      order: 10,
      category: PaletteCategory.Circuits,
      description: "Emits +1 when its pointed side is occupied",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#675d77",
    shadow: "#393345",
    decorationStyle: TileDecorationStyle.Sensor,
    decorationColor: "#d9c8ff",
  },
  [TileKind.FixedCharge]: {
    name: "Fixed Charge Rune",
    boardCode: "1",
    palette: {
      order: 11,
      category: PaletteCategory.Circuits,
      description: "Emits +1 constantly into its welded circuit network",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#6d6047",
    shadow: "#403722",
    decorationStyle: TileDecorationStyle.FixedCharge,
    decorationColor: "#f3dfa0",
  },
  [TileKind.Spark]: {
    name: "Spark Rune",
    boardCode: "K",
    palette: {
      order: 12,
      category: PaletteCategory.Circuits,
      description: "Emits +1 for the first simulation tick, then goes dark",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#665273",
    shadow: "#392d43",
    decorationStyle: TileDecorationStyle.Spark,
    decorationColor: "#ead5ff",
  },
  [TileKind.Inverter]: {
    name: "Inverter Rune",
    boardCode: "I",
    palette: {
      order: 13,
      category: PaletteCategory.Circuits,
      description: "Negates the sum of up to three isolated inputs",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#765878",
    shadow: "#443047",
    decorationStyle: TileDecorationStyle.Inverter,
    decorationColor: "#ead2ef",
  },
  [TileKind.Combiner]: {
    name: "Combiner Rune",
    boardCode: "+",
    palette: {
      order: 14,
      category: PaletteCategory.Circuits,
      description: "Sums up to three isolated inputs toward its output",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#526f69",
    shadow: "#2e413d",
    decorationStyle: TileDecorationStyle.Combiner,
    decorationColor: "#d2f0df",
  },
  [TileKind.Rectifier]: {
    name: "Rectifier Rune",
    boardCode: "R",
    palette: {
      order: 15,
      category: PaletteCategory.Circuits,
      description: "Passes positive sums from up to three isolated inputs",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#786448",
    shadow: "#463821",
    decorationStyle: TileDecorationStyle.Rectifier,
    decorationColor: "#f1dfb8",
  },
  [TileKind.Multiplier]: {
    name: "Multiplier Rune",
    boardCode: "*",
    palette: {
      order: 16,
      category: PaletteCategory.Circuits,
      description: "Multiplies up to three connected isolated inputs",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#51657b",
    shadow: "#2d3a49",
    decorationStyle: TileDecorationStyle.Multiplier,
    decorationColor: "#d4e4f5",
  },
  [TileKind.Subtractor]: {
    name: "Subtractor Rune",
    boardCode: "-",
    palette: {
      order: 17,
      category: PaletteCategory.Circuits,
      description: "Subtracts left and right inputs from the rear input",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#745b50",
    shadow: "#44332c",
    decorationStyle: TileDecorationStyle.Subtractor,
    decorationColor: "#f0d7ca",
  },
  [TileKind.ChargeSensor]: {
    name: "Charge Sensor Rune",
    boardCode: "Q",
    palette: {
      order: 18,
      category: PaletteCategory.Circuits,
      description: "Copies the front tile's charge to three isolated outputs; front welds are non-conductive",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.Up,
    circuitOutputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    magnetic: false,
    attractionRange: 0,
    fill: "#4f6f78",
    shadow: "#2b4047",
    decorationStyle: TileDecorationStyle.ChargeSensor,
    decorationColor: "#d3eff4",
  },
  [TileKind.Selector]: {
    name: "Selector Rune",
    boardCode: "T",
    palette: {
      order: 19,
      category: PaletteCategory.Circuits,
      description: "Selects the left or right input from the rear charge",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#5f587b",
    shadow: "#363047",
    decorationStyle: TileDecorationStyle.Selector,
    decorationColor: "#e2dcfa",
  },
  [TileKind.Equality]: {
    name: "Equality Rune",
    boardCode: "e",
    palette: {
      order: 20,
      category: PaletteCategory.Circuits,
      description: "Outputs +1 when all connected isolated inputs are equal",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#685b78",
    shadow: "#3a3147",
    decorationStyle: TileDecorationStyle.Equality,
    decorationColor: "#e7dcf5",
  },
  [TileKind.Minimum]: {
    name: "Minimum Rune",
    boardCode: "<",
    palette: {
      order: 21,
      category: PaletteCategory.Circuits,
      description: "Outputs the minimum charge among its connected isolated inputs",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#4c6871",
    shadow: "#293d43",
    decorationStyle: TileDecorationStyle.Minimum,
    decorationColor: "#d1edf0",
  },
  [TileKind.Maximum]: {
    name: "Maximum Rune",
    boardCode: ">",
    palette: {
      order: 22,
      category: PaletteCategory.Circuits,
      description: "Outputs the maximum charge among its connected isolated inputs",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#715447",
    shadow: "#412e26",
    decorationStyle: TileDecorationStyle.Maximum,
    decorationColor: "#f0d3c1",
  },
  [TileKind.WireCrossing]: {
    name: "Wire Crossing",
    boardCode: "W",
    palette: {
      order: 23,
      category: PaletteCategory.Circuits,
      description: "Keeps horizontal and vertical circuit networks separate",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#526875",
    shadow: "#2d3b43",
    decorationStyle: TileDecorationStyle.WireCrossing,
    decorationColor: "#d5e9f2",
  },
  [TileKind.Glass]: {
    name: "Glass",
    boardCode: "G",
    palette: {
      order: 5,
      category: PaletteCategory.RawMaterials,
      description: "Solid block baked from sand",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#8ebbc2",
    shadow: "#4e7880",
    decorationStyle: TileDecorationStyle.Crack,
    decorationColor: "#c8edf0",
  },
  [TileKind.IronOre]: {
    name: "Iron Ore",
    boardCode: "O",
    palette: {
      order: 6,
      category: PaletteCategory.RawMaterials,
      description: "Solid ore that a furnace smelts into iron",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#785a49",
    shadow: "#453127",
    decorationStyle: TileDecorationStyle.Grains,
    decorationColor: "#b98766",
  },
  [TileKind.Furnace]: {
    name: "Furnace",
    boardCode: "F",
    palette: {
      order: 7,
      category: PaletteCategory.Mechanisms,
      description: "Bakes the block on its pointed side; rear charge disables it",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.Down,
    circuitOutputPorts: WeldSide.Right | WeldSide.Left,
    magnetic: false,
    attractionRange: 0,
    fill: "#6b5042",
    shadow: "#3e2b23",
    decorationStyle: TileDecorationStyle.Furnace,
    decorationColor: "#f0b25c",
  },
  [TileKind.Conveyor]: {
    name: "Conveyor Belt",
    boardCode: "B",
    palette: {
      order: 8,
      category: PaletteCategory.Mechanisms,
      description: "Charged roller: +1 clockwise, -1 counterclockwise, 0 stopped",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#59636b",
    shadow: "#30383e",
    decorationStyle: TileDecorationStyle.Conveyor,
    decorationColor: "#d6c38b",
  },
  [TileKind.Delivery]: {
    name: "Delivery Box",
    boardCode: "D",
    palette: {
      order: 24,
      category: PaletteCategory.PuzzleTools,
      description: "Absorbs a front welded body exactly matching the body behind it and pulses +1 sideways",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#66513d",
    shadow: "#392b20",
    decorationStyle: TileDecorationStyle.Delivery,
    decorationColor: "#e8c987",
  },
  [TileKind.Victory]: {
    name: "Victory Block",
    boardCode: "V",
    palette: {
      order: 25,
      category: PaletteCategory.PuzzleTools,
      description: "Wins on +1 input or loses on -1 input; opposing inputs jam",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.All,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#5c4f78",
    shadow: "#342b49",
    decorationStyle: TileDecorationStyle.Victory,
    decorationColor: "#eadb88",
  },
  [TileKind.Delay]: {
    name: "Delay Rune",
    boardCode: "Z",
    palette: {
      order: 27,
      category: PaletteCategory.Circuits,
      description: "Delays the isolated rear input by a configurable number of ticks. Press E to configure",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Up | WeldSide.Down,
    circuitInputPorts: WeldSide.Down,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#53677a",
    shadow: "#2d3c49",
    decorationStyle: TileDecorationStyle.Delay,
    decorationColor: "#d3e3f2",
  },
  [TileKind.Counter]: {
    name: "Charge Counter",
    boardCode: "N",
    palette: {
      order: 28,
      category: PaletteCategory.Circuits,
      description: "Adds signed rear inputs and pulses with the wrap direction. Press E to configure",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Up | WeldSide.Down,
    circuitInputPorts: WeldSide.Down,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#645a79",
    shadow: "#393247",
    decorationStyle: TileDecorationStyle.Counter,
    decorationColor: "#eadcf7",
  },
  [TileKind.Rom]: {
    name: "ROM Rune",
    boardCode: "U",
    palette: {
      order: 29,
      category: PaletteCategory.Circuits,
      description: "Positive left/rear inputs move the 2D cursor away from their side; negative inputs reverse it. Outputs the selected value. Press E to configure",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.Left | WeldSide.Down,
    circuitOutputPorts: WeldSide.Up | WeldSide.Right,
    magnetic: false,
    attractionRange: 0,
    fill: "#4f6865",
    shadow: "#2a3d3a",
    decorationStyle: TileDecorationStyle.Rom,
    decorationColor: "#d1ece1",
  },
  [TileKind.Welder]: {
    name: "Welder",
    boardCode: "J",
    palette: {
      order: 30,
      category: PaletteCategory.Mechanisms,
      description: "Welds both transverse edges of the block ahead; -1 side charge disables it",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: true,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.Down,
    magnetic: false,
    attractionRange: 0,
    fill: "#6d5c4b",
    shadow: "#3c3027",
    decorationStyle: TileDecorationStyle.Welder,
    decorationColor: "#f0b85d",
  },
  [TileKind.Splitter]: {
    name: "Splitter",
    boardCode: "X",
    palette: {
      order: 31,
      category: PaletteCategory.Mechanisms,
      description: "Splits both transverse edges of the block ahead; -1 side charge disables it",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: true,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.Down,
    magnetic: false,
    attractionRange: 0,
    fill: "#625669",
    shadow: "#362d3b",
    decorationStyle: TileDecorationStyle.Splitter,
    decorationColor: "#e0b7ee",
  },
  [TileKind.Duplicator]: {
    name: "Duplicator",
    boardCode: "Y",
    palette: {
      order: 32,
      category: PaletteCategory.Mechanisms,
      description: "Mirrors the welded body behind it across itself on +1 side charge",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.Right | WeldSide.Left,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#58666c",
    shadow: "#303a3f",
    decorationStyle: TileDecorationStyle.Duplicator,
    decorationColor: "#c9e4dc",
  },
  [TileKind.Monitor]: {
    name: "Signal Monitor",
    boardCode: "m",
    palette: {
      order: 36,
      category: PaletteCategory.Circuits,
      description: "Joins its welded circuit like a conduit and records that charge every tick on the signal panel. Press E to name its line",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#4f5a6e",
    shadow: "#2b3140",
    decorationStyle: TileDecorationStyle.Monitor,
    decorationColor: "#d8e4f4",
  },
  [TileKind.Grapher]: {
    name: "ROM Grapher",
    boardCode: "g",
    palette: {
      order: 37,
      category: PaletteCategory.Circuits,
      description: "Shows every value of the ROM or sequence checker it points at on the signal panel, marking the cursor. Press E to name its line",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#55646a",
    shadow: "#2e383c",
    decorationStyle: TileDecorationStyle.Grapher,
    decorationColor: "#d6ecea",
  },
  [TileKind.Checker]: {
    name: "Sequence Checker",
    boardCode: "E",
    palette: {
      order: 38,
      category: PaletteCategory.PuzzleTools,
      description: "Waits for the first nonzero rear input, then compares each input with its stored sequence: +1 after a complete match, -1 at the first mismatch. Press E to configure",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Up | WeldSide.Down,
    circuitInputPorts: WeldSide.Down,
    circuitOutputPorts: WeldSide.Up,
    magnetic: false,
    attractionRange: 0,
    fill: "#6a5a3c",
    shadow: "#3a3121",
    decorationStyle: TileDecorationStyle.Checker,
    decorationColor: "#f2dea3",
  },
  [TileKind.RuneArray]: {
    name: "Rune Array",
    boardCode: "A",
    palette: {
      order: 39,
      category: PaletteCategory.Circuits,
      description: "Holds a miniature board whose four edge-center cells connect to its sides with no delay. Press E to configure, Enter to open",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: false,
    circuitPorts: WeldSide.All,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#3d4770",
    shadow: "#212642",
    decorationStyle: TileDecorationStyle.RuneArray,
    decorationColor: "#c7d3f4",
  },
  [TileKind.Assembler]: {
    name: "Assembler",
    boardCode: "H",
    palette: {
      order: 33,
      category: PaletteCategory.Mechanisms,
      description: "Consumes a welded body ahead that matches a recipe in any rotation, then emits the recipe's outputs one per tick behind it",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.Right | WeldSide.Left,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#5f5347",
    shadow: "#342c25",
    decorationStyle: TileDecorationStyle.Assembler,
    decorationColor: "#e2b96a",
  },
  [TileKind.Rotator]: {
    name: "Rotator",
    boardCode: "r",
    palette: {
      order: 34,
      category: PaletteCategory.Mechanisms,
      description: "Turns its gripped body 90° with +1 clockwise or -1 counterclockwise rear input",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.Down,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Down,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#5c5368",
    shadow: "#332d3b",
    decorationStyle: TileDecorationStyle.Rotator,
    decorationColor: "#e1c3f2",
  },
  [TileKind.Piston]: {
    name: "Piston",
    boardCode: "P",
    palette: {
      order: 26,
      category: PaletteCategory.Mechanisms,
      description: "Extends on +1 and retracts on -1; its pointed side is the arm head",
    },
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#67584b",
    shadow: "#382f29",
    decorationStyle: TileDecorationStyle.Piston,
    decorationColor: "#d1aa6b",
  },
  [TileKind.PistonBase]: {
    name: "Piston Base",
    boardCode: "b",
    palette: null,
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.All,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.Right | WeldSide.Down | WeldSide.Left,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#67584b",
    shadow: "#382f29",
    decorationStyle: TileDecorationStyle.PistonBase,
    decorationColor: "#d1aa6b",
  },
  [TileKind.PistonArm]: {
    name: "Piston Arm",
    boardCode: "a",
    palette: null,
    affectedByGravity: true,
    slidesDiagonally: false,
    weldableSides: WeldSide.Up | WeldSide.Down,
    excludesFacingWeld: false,
    usesOrientation: true,
    circuitPorts: WeldSide.None,
    circuitInputPorts: WeldSide.None,
    circuitOutputPorts: WeldSide.None,
    magnetic: false,
    attractionRange: 0,
    fill: "#8b755e",
    shadow: "#4b3d31",
    decorationStyle: TileDecorationStyle.PistonArm,
    decorationColor: "#e3c486",
  },
};

export const TILE_KINDS: readonly TileKind[] = Object.freeze(
  Object.keys(TILE_DEFINITIONS).map((value) => Number(value) as TileKind),
);

function buildTileKindsByBoardCode(): Readonly<Record<string, TileKind | undefined>> {
  const kindsByCode = Object.create(null) as Record<string, TileKind | undefined>;
  for (const kind of TILE_KINDS) {
    const definition = TILE_DEFINITIONS[kind];
    if (definition.boardCode.length !== 1) {
      throw new Error(`Board code for ${definition.name} must be one character`);
    }
    if (Object.hasOwn(kindsByCode, definition.boardCode)) {
      throw new Error(`Duplicate board tile code "${definition.boardCode}"`);
    }
    kindsByCode[definition.boardCode] = kind;
  }
  return kindsByCode;
}

const TILE_KINDS_BY_BOARD_CODE = buildTileKindsByBoardCode();

/** Tile kind for a compact board code, or undefined for an unknown code. */
export function tileKindForBoardCode(code: string): TileKind | undefined {
  return TILE_KINDS_BY_BOARD_CODE[code];
}

export function isTileKind(value: number): value is TileKind {
  return Number.isInteger(value) && Object.hasOwn(TILE_DEFINITIONS, value);
}

export function orientationForKind(kind: TileKind, orientation: Direction): Direction {
  return TILE_DEFINITIONS[kind].usesOrientation ? orientation : Direction.Up;
}

/** Rotates a side mask from its upward-facing definition to a tile's orientation. */
export function orientedSides(sides: WeldSide, orientation: Direction): WeldSide {
  return (
    ((sides << orientation) | (sides >> (4 - orientation))) &
    WeldSide.All
  ) as WeldSide;
}
